name: food_project
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.1.1
  dio: ^3.0.10
  fluttertoast: ^7.1.6
  shared_preferences: ^0.5.12+4
  outline_material_icons: ^0.1.1
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.4+1
  http:
  url_launcher:
  expansion_tile_card: ^1.1.0
  conditional_builder: ^1.0.2
  image_picker: ^0.6.7+22
  firebase_storage: ^5.2.0
  google_sign_in: ^4.5.9
  firebase_in_app_messaging: ^0.2.3
  firebase_messaging: ^7.0.3
  flutter_launcher_icons: ^0.8.1
  flutter_snake_navigationbar: ^0.4.2
  dcdg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

